[versions]
kotlin = "2.0.20"
kotlin-logging = "3.0.5"
kotlinx-coroutines = "1.10.2"
junit-jupiter = "6.0.1"
web3j = "5.0.1"
testcontainers-redis = "2.2.2"
testcontainers-junit-jupiter = "1.19.3"
testcontainers = "1.19.3"
redis-clients = "5.1.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
web3j-core = { module = "org.web3j:core", version.ref = "web3j" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlin-logging" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
redis-clients = { module = "redis.clients:jedis", version.ref = "redis-clients" }

testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "testcontainers-redis" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers-junit-jupiter" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
